### ISSUE TITLE
Hardwarewallet Libraries

### ISSUE THREAD

**Issue by MelbourneDeveloper** [hoardexchange/HoardSDK#1]
Hey there. I noticed that you're using my library Device.Net for hardwarewallet integration. Also, I noticed you've written libraries for Ledger, and Trezor. Did you know about these?

https://github.com/MelbourneDeveloper/Trezor.Net
https://github.com/MelbourneDeveloper/Ledger.Net
https://github.com/MelbourneDeveloper/KeepKey.Net

It looks like that these will be pretty actively developed.

**Comment by MelbourneDeveloper** [comment]
If these libraries aren't what you're looking for, I'd really like to hear about why you couldn't use them.

**Comment by MelbourneDeveloper** [comment]
But, also, great to see that Device.Net is getting used, and please let me know if there's anything to be helped with.

**Comment by Ed-warf** [comment]
Hey!
Our code is based on yours great .net libraries (big kudos for that!). We started using Hid.Net library but it had some issues and we had to write the code for our own. Then we migrated to Usb.Net but in order to keep number of dependencies low we decided not to link to additional ones (especially that the code was working). We might consider using them in future to support additional wallets (like KeepKey).

**Comment by MelbourneDeveloper** [comment]
@ed_warf

Thanks for the feedback. Maintaining these libraries has been difficult and I'm not surprised that there have been issues with hid.net etc. The stack of framework was never meant to end up being split in to so many dependencies. But, I've discovered that splitting the libraries up the way they have been with dependency injection has been the right choice and they are becoming more and more solid all the time. 

I see that th hardwarewallet implementations here are very clean.  I can see that a lot of the complexity has been stripped out. That's a good thing. But I'd really like to work with you and others  so that my hardwarewallet libraries can be used in other projects. I realise that it's necessary to make quick decisions but if I knew why you adding these additional dependencies was a choice, I'd like to see what I can do to increase the chance that they can be reused in future. 

Device.net has undergone some API changes in 3.0 and some small changes in the hardwarewallet libraries will follow so I'm keen to avoid a situation where people find it difficult to upgrade. So basically, stay in touch, tell me your frustrations and feel free to submit PRs. These libraries are a massive undertaking and I need people who can grasp them to help shame them.

**Comment by MelbourneDeveloper** [comment]
@ed-warf lastly, if you could provide a link back to the original Trezor.net and ledger.net code used in your comments, that would be much appreciated. I hope to continue to improve the quality of these libraries and that these libraries be recognised as reference libraries in the long run.

**Comment by Ed-warf** [comment]
Done! I've added links to your original code.
